[package]
name = "filechain"
version = "0.1.0"
edition = "2024"



[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
blake3 = "1.5"
hex = "0.4"
time = "0.3"
sled = "0.34"
ed25519-dalek = "2"
libp2p = { version = "0.53", features = ["gossipsub", "tcp", "dns", "noise", "yamux"] }
axum = "0.7"
tower = "0.5"
uuid = { version = "1", features = ["v4"] }
notify = "6.1"

